/*
 * switches.h
 *
 *  COPYRIGHT : 1989 Echinda.
 * PROGRAMMER : Richard G. Marquez
 *    VERSION : 00.000
 *    CREATED : 12/22/89
 *   MODIFIED : 03/23/92
 *       TABS : 05 09
 *
 *	     \|///-_
 *	     \oo///_
 *	-----w/-w------
 *	 E C H I D N A
 *	---------------
 *
 * DESCRIPTION
 *		User defined switches.
 *
 * HISTORY
 *	12/22/89 Friday - Created. (RGM)
 *
*/
#ifndef SWITCHES_H
#define SWITCHES_H

/**************************** C O N S T A N T S ***************************/
#define ERRORS				1
#define REQUIRE				1
#define NO_ERROR_NUMBERS	0
#define SHOW_MEM			0

#endif /* SWITCHES_H */


