/*
 * SWITCHES.h
 *
 *  COPYRIGHT : 1989 Echinda.
 * PROGRAMMER : Gregg A. Tavares
 *    VERSION : 00.000
 *    CREATED : 12/22/89
 *   MODIFIED : 06/20/91
 *       TABS : 05 09
 *
 *	     \|///-_
 *	     \oo///_
 *	-----w/-w------
 *	 E C H I D N A
 *	---------------
 *
 * DESCRIPTION
 *		
 *
 * HISTORY
 *
*/
#ifndef SWITCHES_H
#define SWITCHES_H

#include <echidna/platform.h>

/******************************** SWITCHES ********************************/
#define ERRORS				1
#define NO_ERROR_NUMBERS	1

#define SHOW_MEM			0
#ifndef DEBUG
#define DEBUG				0
#endif
#define DEBUGGING			0
#define REQUIRE				1

#endif /* SWITCHES_H */

