/*
 * SWITCHES.h
 *
 *  COPYRIGHT : 1989 Echinda.
 * PROGRAMMER : Juan M. Alvarado
 *    VERSION : 00.000
 *    CREATED : 12/22/89
 *   MODIFIED : 05/24/91
 *       TABS : 05 09
 *
 *	     \|///-_
 *	     \oo///_
 *	-----w/-w------
 *	 E C H I D N A
 *	---------------
 *
 * DESCRIPTION
 *		
 *
 * HISTORY
 *
*/
#ifndef SWITCHES_H
#define SWITCHES_H

/******************************** SWITCHES ********************************/
#define ERRORS				1
#define NO_ERROR_NUMBERS	0

#define DEBUGGING			1
#define REQUIRE				1

#endif /* SWITCHES_H */

