/*
 * SWITCHES.H
 *
 *  COPYRIGHT : 1990 Echidna.
 * PROGRAMMER : Gregg A. Tavares
 *    VERSION : 00.000
 *    CREATED : 05/08/90
 *   MODIFIED : 10/04/93
 *       TABS : 05 09
 *
 *	     \|///-_
 *	     \oo///_
 *	-----w/-w------
 *	 E C H I D N A
 *	---------------
 *
 * DESCRIPTION
 *		
 *
 * HISTORY
 *
*/

#ifndef SWITCHES_H
#define SWITCHES_H

/******************************** SWITCHES ********************************/
#define ERRORS				1
#define REQUIRE				1
#define NO_ERROR_NUMBERS	0
#define SHOW_MEM			0

#define	RANGECHECKING		1	// ******** Enable/Disable Range Checking
#define	DEBUG_PRINTFS		1	// ******** Enable/Disable DPRINTF statements
#define	DEBUG_CODE			0	// ******** Debug/Final switch
#define	RUNTIME_CODE		1	// ******** Debug/Final switch

#endif /* SWITCHES_H */



